[project]
name = "tokenizer-hi"
version = "0.1.0"
description = "Tokenizer for the Hindi language, trained on <some> dataset."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kagglehub>=0.4.1",
]
